```{r}
webdriver::install_phantomjs()
library("chromote")
if (!require(remotes)) install.packages("remotes")
remotes::install_github("prioritizr/wdpar@extra-wait")
library(wdpar)
x <- wdpa_fetch("LIE")
```

```{r}
download_wdpa_data <- function(url) {
  # Créer un répertoire temporaire
  temp_dir <- tempdir()
  
  # Déterminer le nom du fichier à partir de l'URL
  file_name <- basename(url)
  dest_file <- file.path(temp_dir, file_name)
  
  # Télécharger le fichier
  download.file(url, dest_file, mode = "wb")
  
  # Retourner le chemin du fichier téléchargé
  return(dest_file)
}

# Utiliser la fonction
url <- "http://wcmc.io/wdpa_current_release"
downloaded_file <- download_wdpa_data(url)
cat("Fichier téléchargé à :", downloaded_file, "\n")

# Créer un répertoire temporaire pour l'extraction
temp_extract_dir <- file.path(tempdir(), "wdpa_extract")
dir.create(temp_extract_dir)

# Décompresser le fichier téléchargé dans le répertoire temporaire
unzip(downloaded_file, exdir = temp_extract_dir)

gdb_path <- file.path(temp_extract_dir, "WDPA_WDOECM_Jun2024_Public.gdb")
layers <- st_layers(gdb_path)
layer_name <- layers$name[1]
data_wdpa <- st_read(dsn = gdb_path, layer = layer_name)
# Supprimer les répertoires temporaires et les fichiers
unlink(temp_extract_dir, recursive = TRUE)
unlink(downloaded_file)
```

```{r}
# Function to dowload data
download_wdpa_data <- function(url, dest_dir) {
  # Vérifiez si le répertoire de destination existe, sinon le créer
  if (!dir.exists(dest_dir)) {
    dir.create(dest_dir, recursive = TRUE)
  }
  
  # Déterminer le nom du fichier à partir de l'URL
  file_name <- basename(url)
  dest_file <- file.path(dest_dir, file_name)
  
  # Télécharger le fichier
  download.file(url, dest_file, mode = "wb")
  
  # Retourner le chemin du fichier téléchargé
  return(dest_file)
}

# using the function 
url <- "http://wcmc.io/wdpa_current_release"
dest_dir <- "/home/onyxia/work/EVA-impact-aires-protegees/data" 

downloaded_file <- download_wdpa_data(url, dest_dir)
cat("Fichier téléchargé à :", downloaded_file, "\n")

unzip(downloaded_file, exdir = "/home/onyxia/work/EVA-impact-aires-protegees/data/")
data_wdpa <- st_read(dsn = "/home/onyxia/work/EVA-impact-aires-protegees/data/WDPA_WDOECM_Jun2024_Public.gdb")

```

